packetbeat.interfaces.device: any  # 捕获所有网卡的网络请求

packetbeat.protocols:
- type: http  
  ports: [10223]            # 被捕获服务的端口
  send_headers: ["User-Agent", "Authorization"]  # header中只捕获列出的字段
  real_ip_header: "X-Forwarded-For"
- type: mysql
  ports: [3306,3307]
  
output.logstash:
  hosts: ["logstash:5044"]
# output.kafka:
#   # initial brokers for reading cluster metadata
#   hosts: ["192.168.100.201:9092"]
#   version: "0.10.2.1"      # Kafka的对应版本
#   # message topic selection + partitioning
#   topic: 'downgrade'
#   partition.round_robin:
#     reachable_only: false
#   required_acks: 1
#   compression: gzip
#   max_message_bytes: 1000000