---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-data-pv-volume
  labels:
    pv: elastic-data-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.2.89
    path: "/home/luqin/data/elasticsearch/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-data-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      pv: elastic-data-pv-volume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-logs-pv-volume
  labels:
    pv: elastic-logs-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.2.89
    path: "/home/luqin/data/elasticsearch/logs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-logs-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      pv: elastic-logs-pv-volume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-config-pv-volume
  labels:
    pv: elastic-config-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.2.89
    path: "/home/luqin/data/elasticsearch/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-config-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: elastic-config-pv-volume
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  type: NodePort
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 9200
    name: s1
  - port: 9300
    targetPort: 9300
    nodePort: 9300
    name: s2
  selector:
    name: elasticsearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      name: elasticsearch
  template:
    metadata:
      labels:
        name: elasticsearch
        group: elastic
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.7.1
        securityContext:
          runAsUser: 1000
        ports:
          - containerPort: 9200
          - containerPort: 9300
        # envFrom:
        #   - configMapRef:
        #       name: datacleaning-proxy-configmaps
        volumeMounts:
          - name: data
            mountPath: /usr/share/elasticsearch/data
          - name: config
            mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            subPath: elasticsearch.yml
          - name: logs
            mountPath: /usr/share/elasticsearch/logs
        # resources:
        #   limits:
        #     cpu: 10
        #     memory: 8096Mi
        #   requests:
        #     cpu: 2
        #     memory: 4096Mi
        # # command: ["sleep", "10000000000000"]
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: elastic-data-pv-claim
        - name: logs
          persistentVolumeClaim:
            claimName: elastic-logs-pv-claim
        - name: config
          persistentVolumeClaim:
            claimName: elastic-config-pv-claim
      # nodeSelector:
      #   datacleaning-proxy: "true"