---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kibana-config-pv-volume
  labels:
    pv: kibana-config-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.2.89
    path: "/home/luqin/data/kibana/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kibana-config-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: kibana-config-pv-volume
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  type: NodePort
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 5601
  selector:
    name: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      name: kibana
  template:
    metadata:
      labels:
        name: kibana
        group: elastic
    spec:
      containers:
      - name: kibana
        image: kibana:7.7.1
        ports:
        - containerPort: 5601
        # envFrom:
        #   - configMapRef:
        #       name: datacleaning-proxy-configmaps
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/config/kibana.yml
          subPath: kibana.yml
        # resources:
        #   limits:
        #     cpu: 10
        #     memory: 8096Mi
        #   requests:
        #     cpu: 2
        #     memory: 4096Mi
        # # command: ["sleep", "10000000000000"]
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: kibana-config-pv-claim
        # nodeSelector:
        #   datacleaning-proxy: "true"