---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logstash-config-pv-volume
  labels:
    pv: logstash-config-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.2.89
    path: "/home/luqin/data/logstash/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logstash-config-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: logstash-config-pv-volume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logstash-confd-pv-volume
  labels:
    pv: logstash-confd-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.2.89
    path: "/home/luqin/data/logstash/conf.d"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logstash-confd-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: logstash-confd-pv-volume
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  type: NodePort
  ports:
  - port: 5044
    targetPort: 5044
    nodePort: 5044
  selector:
    name: logstash
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      name: logstash
  template:
    metadata:
      labels:
        name: logstash
        group: elastic
    spec:
      containers:
      - name: logstash
        image: logstash:7.7.1
        ports:
        - containerPort: 5044
        # envFrom:
        #   - configMapRef:
        #       name: datacleaning-proxy-configmaps
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
        - name: confd
          mountPath: /data/elk/logstash/conf.d
          # subPath: logstash.yml
        # resources:
        #   limits:
        #     cpu: 10
        #     memory: 8096Mi
        #   requests:
        #     cpu: 2
        #     memory: 4096Mi
        # # command: ["sleep", "10000000000000"]
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: logstash-config-pv-claim
      - name: confd
        persistentVolumeClaim:
          claimName: logstash-confd-pv-claim
        # nodeSelector:
        #   datacleaning-proxy: "true"